services:
  mysql-db:
    image: mysql:latest
    container_name: customer-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: customer_db
      MYSQL_USER: customer
      MYSQL_PASSWORD: 1234
    ports:
      - '3307:3306'
    volumes:
      - ./data:/var/lib/mysql-customer
    networks:
      - demo-network
#
#  customer-app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: customer-app
#    depends_on:
#      - mysql-db
#    ports:
#      - '8080:8080'
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/customer-db
#      SPRING_DATASOURCE_USERNAME: customer
#      SPRING_DATASOURCE_PASSWORD: 1234
#    restart: always
#    networks:
#      - demo-network
#
networks:
  demo-network:
    driver: bridge